module.exports = {
    NUMBER: 'NUMBER',
    PLUS_OP: 'PLUS_OP',
    MINUS_OP: 'MINUS_OP',
    MULTIPLY_OP: 'MULTIPLY_OP',
    DIVIDE_OP: 'DIVIDE_OP',
    L_PAREN: 'L_PAREN',
    R_PAREN: 'R_PAREN',
    END: 'END',
    BEGIN: 'BEGIN',
    DOT: 'DOT',
    ASSIGN: 'ASSIGN',
    SEMI: 'SEMI',
    ID: 'ID',
    EOF: 'EOF',
}